[2158] Replace terrafile
DFE-Digital/cpd-information pull request #66
Opened 2024-11-29 16:50 UTC by saliceti

## Description
terrafile is no longer maintained

## How to review
make domains-infra-plan
make production domains-plan CONFIRM_PRODUCTION=y

## After merge
Apply to production

2024-11-29 16:50 UTC, saliceti commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace terrafile](https://trello.com/c/5jCq2a3p/2158-replace-terrafile)

2024-12-02 11:54 UTC, neillturner requested changes
make domains-infra-plan
make production domains-plan CONFIRM_PRODUCTION=y

2024-12-02 12:17 UTC, saliceti commented
> does global_config/production.sh need added TERRAFORM_MODULES_TAG=stable ?
There is only 1 domain. It worked as it was using TERRAFORM_MODULES_TAG from domains.sh. But since there might be another doain later on, added to production.sh too.

2024-12-02 12:37 UTC, neillturner approved these changes

2024-12-02 13:20 UTC, merged